### ISSUE TITLE
add resize() to h5pyswmr.Dataset

### ISSUE THREAD

**Issue by RomanKosobrodov** [meteotest/h5pySWMR#6]
Provide support for resizable datasets. Using HDF5 to store input data/measurements that arrive in real time is a common application of SWMR that requires resizable datasets.

**Comment by weatherfrog** [comment]
I was happy to accept your pull request. Thanks!

Btw, we're working on an hdf5 client/server application that's going to supersede the h5pyswmr package:
https://github.com/meteotest/hurray (very much work in progress)
